name: Fluxo de integração

on: [push, pull_request, workflow_dispatch]

jobs:
  testes_automatizados:
    name: testes automatizados
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: configuração do python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: raspberry/requirements.txt

      - name: "executar testes: Raspberry"
        working-directory: raspberry
        run: |
          pip install -r requirements.txt
          python -m pytest